app/urls.py
from django.conf.urls import url, include
from .views import *
from django.conf import settings

app_name = 'notes'
urlpatterns = [
    url(r'^notes/$', NotesView.as_view(), name='note'),
    url(r'^delete/(?P<id>[0-9]+)/$', DeleteView.as_view(), name='delete'),
    url(r'^edit/(?P<id>[0-9]+)/$', EditView.as_view(), name='edit'),
]

demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/',include('app.urls')),
] 

app/models.py
from django.db import models

# Create your models here.
class Notes(models.Model):
    notes = models.CharField(max_length=300)
    title = models.CharField(max_length=40)
    date = models.DateTimeField(auto_now_add=True)

app/forms.py
from django import forms
from .models import Notes

class NotesForm(forms.ModelForm):
    class Meta:
        model = Notes
        fields = ['notes','title']
        lables = {
            'notes': 'Note',
            'title' : 'Title',
            }

app/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import *
from .forms import NotesForm
from .models import Notes
from django.urls import reverse

class NotesView(View):
    def get(self, request):
        form = NotesForm()
        note = Notes.objects.all().order_by("-date")
        return render(request, 'app/note.html', {'form': form, 'note': note})

    def post(self, request):
        form = NotesForm(request.POST)
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return HttpResponseRedirect(reverse('notes:note'))
        else:
            form = NotesForm(request.POST)
            return HttpResponseRedirect(request, 'app/note.html', {'notes': form})  


class DeleteView(View):
    def get(self, request, id):
        form = Notes.objects.get(id=id).delete()
        return HttpResponseRedirect(reverse('notes:note'))
        
class EditView(View):
    def get(self, request, id):
        try:
            note = Notes.objects.get(id=id)
        
            form = NotesForm(instance = note)
            return render(request, 'app/edit.html', {'form': form, 'note': note})

        except Notes.DoesNotExist:
            return render(request, 'app/404.html')    

    def post(self, request, id):
        form = NotesForm(request.POST, instance= Notes.objects.get(id=id)) 
        if form.is_valid():
            data = form.save(commit=False)
            data.save()
            return HttpResponseRedirect(reverse('notes:note'))        

app/templates/app/edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>I2V - Onboarding System</title>
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" />
    <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="
        crossorigin="anonymous"></script> -->
        <link rel="stylesheet" type="text/css" href="{% static 'app/index.css' %}  " />
</head>
<style>


</style>

<body>
        
        <form enctype="multipart/form-data" method="post">{% csrf_token %}
        
            <!-- {{ form.notes.label_tag }} {{ form.notes.errors }} {{ form.notes }} -->
            <div class="row">
            
            {{ form }}
            
        
        <input name="form_save" class="button-primary" type="submit" value="save" />
    </div>

        
        </form>
   </body>
   </html>     

app/templates/app/note.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>I2V - Onboarding System</title>
    <!-- <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" />
    <script src="https://code.jquery.com/jquery-2.2.2.min.js" integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="
        crossorigin="anonymous"></script> -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'app/index.css' %}  " />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        
</head>

<body>
        
        <form enctype="multipart/form-data" method="post">{% csrf_token %}
        
            <!-- {{ form.notes.label_tag }} {{ form.notes.errors }} {{ form.notes }} -->
            <div class="row">
            {{ form.title.label_tag }} {{ form.title.errors }} {{ form.title }}
            
            <label for="notes">Note</label>
            <textarea type="text" rows="10" cols="40" name="notes" value="notes"></textarea>
            
        
        <input type="submit" value="save" />
    </div>

        
        </form>
        <div class="row">
            
        {% for getnote in note %}
        <div class="border" >

                <fieldset class="majorpoints">
                        <div class="majorpointslegend">
                        
            
            <span>Title:</span>
        <span>{{ getnote.title }}</span > <span class="center">{{ getnote.date }}</span> <a href="{% url 'notes:delete' getnote.id %}">X</a>
        <a href="{% url 'notes:edit' getnote.id %}">Edit</a>
                        </div>
                        
        <div class="hiders" style="display:none" >
                {{ getnote.notes}}
            </div>
            {% endfor %}
    </div>
    
   </body>
   <script>
   $('.majorpoints').click(function(){
    $(this).find('.hiders').toggle();
});
   </script>
   </html>     